image: node:latest

pipelines:
  branches:
    master:
      - step:
          deployment: production
          name: Deploy to production
          caches:
            - node
          script:
            - npm install
            - npm run build
            - scp -r ./$BUILD_DIR $USER@$HOST:$SITE_ROOT
    develop:
      - step:
          deployment: devaid
          name: Deploy to devaid
          caches:
            - node
          script:
            - npm install
            - npm run build
            - scp -r ./$BUILD_DIR $USER@$HOST:$SITE_ROOT